### ISSUE TITLE
Issues with CT since Hubitat 2.2.8 Update

### ISSUE THREAD

**Issue by jeanofthedead** [zranger1/HubitatWizLightDriver#5]
Hey zranger,

I'm getting the following error when trying to set ColorTemperature values on my Wiz bulbs in Hubitat ever since today's Hubitat update:

```
groovy.lang.MissingMethodException: No signature of method: user_driver_ZRanger1_Wiz_Color_Light_435.setColorTemperature() is applicable for argument types: (java.lang.Integer, java.lang.Integer) values: [6010, 100]
Possible solutions: setColorTemperature(java.lang.Object) (setColorTemperature)
```

Thanks for looking into this. Love your driver!

**Comment by zranger1** [comment]
Thanks for reporting this!   I just posted a fix.  The package manager should pick it up shortly, or you can grab the source code from the repository.

-- the explanation --
Somewhere around firmware 2.2.6, the Hubitat guys changed the number of parameters to the setColorTemperature() capability.  In 2.2.8, they implemented the new method in all their internal apps, and it finally broke drivers that hadn't yet added the new API.   I didn't see this because I was still running 2.2.7.  I usually wait a few days on firmware updates, because there's usually another one coming...   Anyway, it should be OK now.  Thanks again for letting me know!
